/*
""layout.js""

File blueprint  for a webpage, deciding how elements
like headers and footers come together.
It ensures a consistent look, includes reusable parts,
styling details, and handles data loading.
It's like the master plan for a well-designed website.
*/



import { Inter } from 'next/font/google'
import "bootstrap/dist/css/bootstrap.min.css"
import './globals.css'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MOVIE VERSE',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <main>{children}</main></body>
    </html>
  )
}
